### ISSUE TITLE
Our Team - Team Member Light Box - Can you please decrease the size of this to look more like the design? 

### ISSUE THREAD

**Issue by tgascoigne14** [CCI-Studios/RE-Dale#1]
Right now it looks like the screenshot. We need to be able to see more than the image when the light box loads.
![screen shot 2015-10-13 at 4 23 41 pm](https://cloud.githubusercontent.com/assets/8631079/10467287/e73f52b2-71c6-11e5-932b-efe5114e7e41.png)

**Comment by hemantcci** [comment]
I have reduced the size let me know how it looks in your screen now.
